version: '3'
services:
  spark-master:
    image: bde2020/spark-master:3.0.1-hadoop3.2
    container_name: spark-master
    ports:
      - 8080:8080
    environment:
      - ENABLE_INIT_DAEMON=false
    networks:
      spark-cluster:
        aliases:
          - spark-master
  spark-worker-1:
    image: bde2020/spark-worker:3.0.1-hadoop3.2
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - 8081:8081
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - ENABLE_INIT_DAEMON=false
    networks:
      spark-cluster:
        aliases:
          - spark-worker-1
  spark-disjoint-ranges:
    image: spark-disjoint-ranges
    build:
      context: .
    container_name: spark-disjoint-ranges
    depends_on:
      - spark-master
      - spark-worker-1
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - ENABLE_INIT_DAEMON=false
      - IP_RANGES_COUNT=100
    networks:
      spark-cluster:
        aliases:
          - spark-disjoint-ranges
  postgres-db:
    image: postgres:10
    volumes:
      - spark-postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    networks:
      spark-cluster:
        aliases:
          - postgres
  elasticsearch:
    image: elasticsearch:7.9.3
    environment:
      - discovery.type=single-node
    volumes:
      - spark-elasticsearch-data:/usr/share/elasticsearch/data
    ports:
    - 9200:9200
    networks:
      spark-cluster:
        aliases:
          - elasticsearch

networks:
  spark-cluster:

volumes:
  spark-postgres-data:
  spark-elasticsearch-data: