version: '3'
services:
  spark-master:
    image: bde2020/spark-master:3.0.1-hadoop3.2
    container_name: spark-master
    ports:
      - "8080:8080"
    environment:
      - ENABLE_INIT_DAEMON=false
    networks:
      spark:
        aliases:
          - spark-master
  spark-worker-1:
    image: bde2020/spark-worker:3.0.1-hadoop3.2
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - ENABLE_INIT_DAEMON=false
    networks:
      spark:
        aliases:
          - spark-worker-1
  spark-disjoint-ranges:
    image: spark-disjoint-ranges
    build:
      context: .
    container_name: spark-disjoint-ranges
    depends_on:
      - spark-master
      - spark-worker-1
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - ENABLE_INIT_DAEMON=false
    networks:
      spark:
        aliases:
          - spark-disjoint-ranges
networks:
  spark: